### ISSUE TITLE
Consider better separation of modifications from additions. 

### ISSUE THREAD

**Issue by iislucas** [conversationai/wikidetox#21]
Consider if we can separate edits to others comments as there seem to actually be quite a few. We should investigate conversations like conversation id: 85577055.2121.2121  

For minor edits, ideally we'd show the main author, and then just say minor edits by ... , and perhaps even underline the bits that are different in some way.

**Comment by vegetable68** [comment]
Showing which bits edited by whom is a bit hard to implement but adding a list of contributors can be done quite quickly.

**Comment by iislucas** [comment]
Maybe we can show who the original author is and then just note (also edited by ...) ?
