### ISSUE TITLE
Ingestion Failure Examples

### ISSUE THREAD

**Issue by vegetable68** [conversationai/wikidetox#58]
Ingestion failed on the 7z files listed here:

https://github.com/conversationai/wikidetox/blob/dataflow_pipeline/conversation_reconstruction_dataflow/ingest_revisions/input_lists/7z_file_list_stuck

- The ParDo operation gets stuck(doesn't seem to output results to WriteToBigQuery)
- No errors prompted on dataflow

**Comment by iislucas** [comment]
Initial observations (based on finding these files in storage: gs://wikidetox-viz-dataflow/raw-downloads)

These two files in particular are much larger than the others (by up to 5x); which suggests that, 1. we should expect them to take up to 5x longer, and 2. we need to worry a bit more about memory (they'll be approx. 55GB uncompressed)
